Missionframework/presets/rhs.sqf
Missionframework/presets/rhs_bw.sqf
Missionframework/presets/rhs_takistan.sqf

Update statics to use assets from RHS mod.
Also sets M119 howtizer as unlockable asset.

Update statics in RHS presets

---

Missionframework/scripts/shared/kill_manager.sqf

Fix UAV unconnectable after player death

---

Missionframework/scripts/server/ai/building_defence_ai.sqf

sometimes enemy when exposed to the BLUFOR fire , didn't react but begin to "dance" on their position. this little fix make the cqb in big town more realistic.

Fix - Enemy Weapon Dance In Hand

---

README.md

I love playing this mission with my clan, then I want to give my contribution to your project, I made a full translation of the mission in italian to give the possibility to my compatriots to better understand the mission. @Wyqer if you decide to add more text in the mission contact me I will help you in the translation.

Full Italian Translation of the mission

---

Missionframework/scripts/shared/functions/F_correctLaserBatteries.sqf

Update laser batteries correction script for apex designators.

Fix missing batteries with Apex laser designators

---

Missionframework/stringtable.xml

I have added all the string that were needed for the spanish translation.

Update to spanish language

---

Missionframework/stringtable.xml
README.md

update italian language and readme.md with new link to my repo.

Update italian lenguage

---

Missionframework/stringtable.xml

Update Italian Localization

---

Missionframework/init.sqf
Missionframework/kp_liberation_config.sqf
Missionframework/presets/3cBAF.sqf
Missionframework/presets/apex_tanoa.sqf
Missionframework/presets/custom.sqf
Missionframework/presets/rhs.sqf
Missionframework/presets/rhs_bw.sqf
Missionframework/presets/rhs_takistan.sqf

All are exactly the same structure and 'level of difficulty' now.

Presets overhaul. :) 

---

Missionbasefiles/kp_liberation.Altis/mission.sqm
Missionbasefiles/kp_liberation.Sara/mission.sqm
Missionbasefiles/kp_liberation.Tanoa/mission.sqm

Removed empty compositions, pointless clutter and pointless statics. Updated the Tanoan USS with the same ol' clutter. :))

Map edits for Altis, Sahrani and Tanoa.

---

Missionframework/stringtable.xml

Update italian localization for the new 0.951

Update italian localization for the new 0.951

---

Missionframework/stringtable.xml

little update for the new v0.952

update the italian localization

---

Missionframework/stringtable.xml

german translation for the tutorial at main base

Madpat3 patch 2

---

Missionframework/scripts/shared/fetch_params.sqf
Missionframework/scripts/shared/set_skill.sqf
Missionframework/stringtable.xml
Missionframework/ui/mission_params.hpp

This pull request adds parameter which disables AI skill changes. This allows to increase difficulty and have more challenging gameplay with more enemies without them being laser accurate with any weapon.

Add param to disable AI skill overwriting

---

Missionframework/stringtable.xml

update italian localization and some lenguage tweak

update italian localization and some lenguage tweak

---

Missionframework/stringtable.xml

Merged from 0.955 version of localization and tweaked/added from 0.96's strings
移植自0.955版本并调整/添加了0.96文本

0.96 Added Chinese Simplified localization

---

Missionframework/kp_liberation_config.sqf
Missionframework/scripts/client/misc/synchronise_vars.sqf
Missionframework/scripts/client/ui/ui_manager.sqf
Missionframework/scripts/server/game/save_manager.sqf
Missionframework/scripts/server/game/synchronise_vars.sqf
Missionframework/scripts/shared/kill_manager.sqf
Missionframework/ui/liberation_titles.hpp

* global variable
* ui element
* kill manager handling
* penalty variable in config
* reordered ui elements
* sync extended for civ rep

Implementation of Civ Rep Global

---

Missionframework/GREUH/Scripts/GREUH_actionmanager.sqf
Missionframework/GREUH/UI/GREUH_interface.hpp
Missionframework/stringtable.xml

Overhauled GREUH menu part to make it "localizable" and added corresponding keys in stringtable.
Fixed missing brackets that I accidentally deleted during translation, also polished many sentences to improve readiness.

V0.96 overhauled GREUH for localization

---

Missionframework/scripts/client/build/do_build.sqf
Missionframework/scripts/server/game/save_manager.sqf

demanufacture garage works with ace-repair, now. no need for building a repair vehicle.

ace compatibility for "demanufacture garage"

---

Missionframework/presets/resistance/rhs_gref.sqf

preset for the resistance faction using RHS:GREF and some RHS:AFRF items

RHS:GREF resistance preset

---

Missionframework/presets/resistance/rhs_gref.sqf

previously submitted to "master" on accident
fixed incorrect ammotypes and removed some of the hats because they look dumb

fixed ammotypes and removed some gear

---

Missionframework/stringtable.xml

Update Italian Localization for v0.961

Update Italian Localization for v0.961

---

Missionframework/stringtable.xml

finished localization for all new strings, and fixed an error made before

Updated Chinese Simplified strings

---

Missionframework/stringtable.xml

Hi Wyqer,
just changed some minor typos.
gqgunhed (DE)

fixed typos, changed some German translation

---

Missionframework/presets/blufor/rhs_afrf.sqf

Add _Grad_ artillery as elite vehicle to afrf preset.

Add BM-21 Grad to AFRF preset

---

Missionframework/stringtable.xml

- Adapted some translations for better understanding;
- Some words were too big to fit on some buttons.

Updated and corrected some portuguese words

---

Missionbasefiles/kp_liberation.lythium/mission.sqm

Just an aesthetic change for slower loading rigs/local machines. Player units now face inland. :wink:

Spawn rotation.

---

Missionframework/scripts/client/build/build_lower.sqf
Missionframework/scripts/client/build/build_raise.sqf
Missionframework/scripts/client/build/do_build.sqf

I added a Raise and Lower user action when building.
The actions don't have icons like the Rotate and Cancel do.

Added Raise/Lower to build script

---

.gitignore
build.bat

Uses the free version of makepbo
https://armaservices.maverick-applications.com/Products/MikerosDosTools/FileBrowserFree
By simply doubleclicking the build.bat all missions will be generated from the current Missionframework files.

Build script

---

Missionframework/presets/opfor/SLA.sqf
Missionframework/presets/resistance/RACS.sqf

Ok, I think I got it this time, please forgive me getting it wrong I'm still trying to figure out how to use GitHub. I think I have it right this time, it's only showing me the 2 files below so fingers crossed hahaha
cheers mate

New presets for Sahrani

---

Missionframework/modules/00_init/fnc/fn_init_receiveInit.sqf
Missionframework/modules/00_init/globals.sqf
Missionframework/modules/01_core/fnc/fn_core_cinematic.sqf
Missionframework/modules/01_core/fnc/fn_core_intro.sqf
Missionframework/modules/01_core/fnc/fn_core_redeploy.sqf
Missionframework/modules/01_core/fnc/fn_core_spawnCam.sqf
Missionframework/modules/01_core/fnc/fn_core_spawnPotato.sqf
Missionframework/modules/01_core/fnc/fn_core_spawnStartVeh.sqf
Missionframework/modules/01_core/fnc/fn_core_spawnVehicle.sqf
Missionframework/modules/01_core/functions.hpp
Missionframework/modules/01_core/globals.sqf
Missionframework/modules/01_core/initModule.sqf

| Q | A |
| --- | --- |
| Fixed issues | #390 |
The spawn functions for the vehicles at the USS Freedom / Chimera base

Spawn of start vehicles and potato 01

---

Missionframework/modules/00_init/fnc/fn_init_save.sqf
Missionframework/modules/01_core/fnc/fn_core_spawnVehicle.sqf
Missionframework/onPlayerRespawn.sqf
Missionframework/stringtable.xml

| Q | A |
| --- | --- |
| Fixed issues | #404 |
Small tweaks which can be done before the sprint ends.

V0.97 small sprint tweaks

---

.vscode/settings.json
Missionframework/modules/00_init/fnc/fn_init_configGuard.sqf
Missionframework/modules/00_init/ui/KPLIB_baseclasses.hpp
Missionframework/modules/00_init/ui/KPLIB_defines.hpp
Missionframework/modules/01_core/fnc/fn_core_redeploy.sqf
Missionframework/modules/01_core/ui/KPLIB_redeploy.hpp
Missionframework/modules/01_core/ui/KPLIB_uiClasses.hpp
Missionframework/stringtable.xml

| Q | A |
| --- | --- |
| Fixed issues | #428 |
The design of the redeploy dialog is now tweaked to the basic ArmA 3 design to achieve a more "native design" in connection to the normal A3 UI. It's a first iteration of basic numbers for spacings, etc. and will get another tweak in the future, I guess.

Redeploy Dialog in A3 design

---

.travis.yml
Missionframework/GREUH/GREUH_config.sqf

| Q | A |
| --- | --- |
| New feature? | no
| Needs wipe? | no
* Fixes encoding issue in GREUH
* Install and Script will always run, Deploy only for tagged commits

Travis CI linting of SQF files

---

.vscode/settings.json

| Q | A |
| --- | --- |
| Needs wipe? | no|
Due to constantly forgetting to update functions header "Last Updated" date when editing them, I wanted to automate this task. I've found VS Code [extension](https://marketplace.visualstudio.com/items?itemName=psioniq.psi-header) that does exactly this and also generates file headers for newly created files.
This pull request contains configuration for said extension, set to create headers compatible with current format.

Add configuration for VS Code "psioniq File Header" extension

---

Missionframework/modules/01_core/fnc/fn_core_intro.sqf
Missionframework/modules/01_core/ui/KPLIB_introMenu.hpp
Missionframework/modules/01_core/ui/KPLIB_titles.hpp
Missionframework/modules/02_respawn/fnc/fn_respawn_onKilled.sqf

| Q | A |
| --- | --- |
| Fixed issues | #494 |
Fixed the broken intro cinematic, which was caused by removing the dependency/inheritance from A3 classes.

Fixed intro cinematic

---

.circleci/config.yml
Missionframework/KPLIB_debriefs.hpp
Missionframework/modules/04_build/fnc/fn_build_drawBoundingBox.sqf
Missionframework/modules/06_virtual/fnc/fn_virtual_curatorAreaLimit.sqf
Missionframework/presets/armies/csat.sqf
Missionframework/presets/armies/customEast.sqf
Missionframework/presets/armies/customWest.sqf
Missionframework/presets/armies/nato.sqf
tools/config_style_checker.py
tools/sqf_validator.py

| Q | A |
| --- | --- |
| Fixed issues | #480 |
SQF and Config style checkers based on ACE project template tools via CircleCI. 
Thanks for the suggestion @bux

CI Syntax and config style checks

---

Missionframework/stringtable.xml

Add Chinese (traditional Chinese) localization.
| Q | A |
| --- | --- |
| Fixed issues | #...  |
add Chinese localization (traditional Chinese)
all english description translated as traditional Chinese

Add Chinese localization.

---

Missionframework/modules/01_common/fnc/fn_common_createCrew.sqf
Missionframework/modules/14_virtual/fnc/fn_virtual_preInit.sqf
Missionframework/modules/15_build/fnc/fn_build_changeQueueMode.sqf
Missionframework/modules/15_build/fnc/fn_build_confirmSingle.sqf
Missionframework/modules/15_build/fnc/fn_build_start.sqf
Missionframework/modules/15_build/fnc/fn_build_stop.sqf

| Q | A |
| --- | --- |
| Bug fix? | yes|
| Fixed issues | #545  |
* NONE

Fix UAVs being created without crew

---

Missionframework/modules/11_permission/fnc/fn_permission_checkVehiclePermission.sqf
Missionframework/modules/11_permission/fnc/fn_permission_postInit.sqf
Missionframework/modules/11_permission/fnc/fn_permission_preInit.sqf
Missionframework/modules/11_permission/fnc/fn_permission_setupPermissionControls.sqf
Missionframework/modules/11_permission/fnc/fn_permission_syncClients.sqf
Missionframework/modules/11_permission/functions.hpp
Missionframework/modules/12_arsenal/fnc/fn_arsenal_fillArsenal.sqf
Missionframework/modules/16_garrison/functions.hpp
Missionframework/stringtable.xml

| Q | A |
| --- | --- |
| Fixed issues | #562  |
This PR fixes some reported Issues from the S9 review.
* ACE

S9 Bugfixes

---

.circleci/config.yml

| Q | A |
| --- | --- |
| Fixed issues | |
To avoid failing CI

Add basic CircleCI config

---

Missionframework/arsenal_presets/gm_west.sqf
Missionframework/kp_liberation_config.sqf
Missionframework/scripts/client/init_client.sqf

| Q | A |
| --- | --- |
| Fixed issues | |
* GM

Arsenal for West Germany in Global Mobilization DLC

---

Missionframework/modules/14_virtual/fnc/fn_virtual_curatorAreaLimit.sqf
Missionframework/modules/14_virtual/fnc/fn_virtual_preInit.sqf

| Q | A |
| --- | --- |
| Needs wipe? | no|
| Fixed issues | #585 |
Curator camera height bugfix
* NONE

S11 Review - Calculate limited curator camera max height from terrain height

---

.circleci/config.yml
.gitignore
tools/build.bat
tools/buildtool/README.md
tools/buildtool/_presets.json
tools/buildtool/gulpfile.ts
tools/buildtool/package-lock.json
tools/buildtool/package.json
tools/buildtool/src/Config.ts
tools/buildtool/src/MissionPaths.ts
tools/buildtool/src/index.ts
tools/buildtool/tsconfig.json

| Q | A |
| --- | --- |
| Fixed issues | -|
Port of node based build tool for 0.97

Port node build tool to 0.97

---

Missionframework/KPGUI/KPGUI_defines.hpp

| Q | A |
| --- | --- |
Removes an invisible character in the UI defines.

Remove invisible U+202C character from KPGUI_defines

---

Missionframework/modules/11_permission/README.md
Missionframework/modules/11_permission/fnc/fn_permission_addPermissionHandler.sqf
Missionframework/modules/12_arsenal/README.md
Missionframework/modules/23_logistic/README.md
Missionframework/modules/23_logistic/fnc/fn_logistic_postInit.sqf
Missionframework/modules/26_cratefiller/README.md
Missionframework/modules/26_cratefiller/fnc/fn_cratefiller_postInit.sqf
Missionframework/modules/26_cratefiller/fnc/fn_cratefiller_preInit.sqf
Missionframework/modules/26_cratefiller/fnc/fn_cratefiller_settings.sqf
Missionframework/modules/README.md

| Q | A |
| --- | --- |
| Fixed issues | #508 |
Various documentation work on the new framework.

Documentation pt.2

---

Missionframework/arsenal_presets/sfp.sqf
Missionframework/kp_liberation_config.sqf
Missionframework/presets/blufor/sfp_des.sqf
Missionframework/presets/blufor/sfp_wdl.sqf
Missionframework/presets/init_presets.sqf
Missionframework/scripts/client/init_client.sqf
README.md

| Q | A |
| --- | --- |
| Fixed issues |  |
Preset for https://steamcommunity.com/sharedfiles/filedetails/?id=826911897

SFP Preset

---

_tools/_presets.json
_tools/gulpfile.ts
_tools/package-lock.json
_tools/package.json
_tools/src/Config.ts

| Q | A |
| --- | --- |
| Bug fix? |  no |
Adds `mapDisplay` property to build tool configuration. Optional property for maps that have "not pretty" config name.
Sets value of ~~`STR_MISSION_VERSION`~~`STR_MISSION_TITLE` on build to `CTI 34 KP Liberation ${preset.mapDisplay || preset.map} ${version}`, version is fetched from `STR_MISSION_VERSION`.

v0.96.5 - Update build tool

---

Missionframework/presets/resistance/unsung.sqf

| Q | A |
| --- | --- |
Added unsung resistance preset.

Unsung Resistance Preset

---

Missionframework/stringtable.xml

| Q | A |
| --- | --- |
Fixed more typos and added missing russian translations. Sorry for not making it into 1 PR :(

Fix more typos and add missing translations

---

_tools/gulpfile.ts

v0.96.7 - Add version hash to PR built PBOs

---

Missionframework/stringtable.xml

| Q | A |
| --- | --- |
| Bug fix? |  no |
| Fixed issues | None |
I was going to add the ~50 missing Turkish strings for hacktoberfest and call it a day, but once I opened the stringtable and saw the previous translations, I knew I had to redo the whole thing. Don't have time to finish all of them, so I want to get this half of it merged in case I can't finish.

Update Turkish Translations Part 1

---

Missionframework/kp_liberation_config.sqf
Missionframework/scripts/client/actions/action_manager.sqf
Missionframework/scripts/client/build/do_sector_build.sqf
Missionframework/scripts/server/game/periodic_save.sqf
README.md

| Q | A |
| --- | --- |
| Fixed issues | #661, #671, #692 |
Small fixes requested/reported by tickets.

Small additions for 0.96.7

---

README.md

- title
- I can't commit to protected branches

Add RHS transport config fixes to change-log

---

.gitignore
README.md
_tools/README.md
_tools/_presets.json
_tools/gulpfile.ts
_tools/src/Config.ts
_tools/src/KpSteam.ts
_tools/src/index.ts
_tools/tsconfig.json

| Q | A |
| --- | --- |
| Needs wipe? | - |
Support for KP-Steam mission uploading in our mission build scripts in legacy branch.

Build tool auto upload

---

.gitignore
tools/buildtool/README.md
tools/buildtool/_presets.json
tools/buildtool/gulpfile.ts
tools/buildtool/src/Config.ts
tools/buildtool/src/KpSteam.ts
tools/buildtool/src/index.ts
tools/buildtool/tsconfig.json

| Q | A |
| --- | --- |
| Needs wipe? | - |
Support for KP-Steam mission uploading in our mission build scripts in rewrite branch.

Build tool auto upload 0.97

---

Missionframework/CfgFunctions.hpp
Missionframework/functions/fn_createClearance.sqf
Missionframework/functions/fn_createClearanceConfirm.sqf
Missionframework/scripts/client/actions/action_manager.sqf
Missionframework/stringtable.xml
README.md

| Q | A |
| --- | --- |
| Fixed issues | #713 |
Adds a dialog before creating the clearance around a FOB to avoid mistakes by "what is this doing?" clicks.

0.96.7 Confirmation dialog for create clearance

---

Missionframework/functions/fn_setDiscordState.sqf
Missionframework/scripts/client/misc/playerNamespace.sqf
Missionframework/scripts/client/ui/ui_manager.sqf

| Q | A |
| --- | --- |
The state update for the [Discord Rich Presence Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1493485159) from @ConnorAu is moved from ui_manager to playerNamespace and got automatic recognition of the state, if no state is given in the call.

0.96.7 Discord Update to playerNamespace

---

Missionframework/scripts/client/init_client.sqf
Missionframework/scripts/server/CfgFunctions.hpp
Missionframework/scripts/server/highcommand/fn_highcommand.fsm
Missionframework/scripts/server/init_server.sqf
Missionframework/scripts/shared/fetch_params.sqf
Missionframework/stringtable.xml
Missionframework/ui/mission_params.hpp
README.md

| Q | A |
| --- | --- |
Adds the old High Command module, as it was requested by some people here and there.
Couldn't remember it was really that useless in comparison to e.g. Zeus or something like C2. Last time I used it was in Arma 2.

0.96.7 A3 High Command

---

Missionframework/scripts/server/highcommand/fn_highcommand.fsm
Missionframework/scripts/server/sector/fn_sectorMonitor.fsm

| Q | A |
| --- | --- |
Small tweaks after some dedicated server test runs.

0.96.7 dedicated test tweaks

---

Missionframework/scripts/server/ai/battlegroup_ai.sqf
Missionframework/scripts/server/battlegroup/spawn_battlegroup.sqf

| Q | A |
| --- | --- |
Small adjustments after a longer session on a dedicated server.
See commit titles

0.96.7 next fixes

---

Missionframework/functions/fn_getSaveData.sqf
Missionframework/functions/fn_getSectorOwnership.sqf
Missionframework/scripts/server/battlegroup/spawn_battlegroup.sqf
Missionframework/scripts/server/sector/fn_spawnSectorCrates.sqf

| Q | A |
| --- | --- |
And a next batch of small fixes after some playing on a dedicated server.
Commit titles

0.96.7 More small fixes

---

Missionframework/CfgFunctions.hpp
Missionframework/description.ext
Missionframework/scripts/client/CfgFunctions.hpp
Missionframework/scripts/client/init_client.sqf
Missionframework/scripts/client/tutorial/CfgTaskDescriptions.hpp
Missionframework/scripts/client/tutorial/fn_tutorial.fsm
Missionframework/scripts/server/CfgFunctions.hpp
Missionframework/scripts/server/base/startgame.sqf
Missionframework/scripts/shared/fetch_params.sqf
Missionframework/stringtable.xml
Missionframework/ui/mission_params.hpp

| Q | A |
| --- | --- |
Adds an interactive tutorial which works via tasks.
Currently the start of the mission with FOB deployment, build storage area and collect start resources is implemented (First FOB Path).
Most likely it won't be expanded further in 0.96.7, but provide a foundation for further paths in a 0.96.8.

0.96.7 Interactive ingame tutorial

---

Missionframework/functions/fn_doSave.sqf
Missionframework/init.sqf
Missionframework/presets/init_presets.sqf

| Q | A |
| --- | --- |
Title. Not adding to changelog as it can be treated as part of saving improvements.

Block saving if framework not initialized properly

---

CHANGELOG.md
Missionframework/kp_objectInits.sqf

Arsenal crate ViV

---

Missionframework/description.ext
Missionframework/scripts/server/battlegroup/readiness_increase.sqf

| Q | A |
| --- | --- |
| Bug fix? | yes / no |
| New feature? | yes / no  |
Allow function recompilation in 3DEN Editor. Also fixed some `isNil` check.

Allow recompile in editor and fix typo

---

.vscode/settings.json
CHANGELOG.md
Missionframework/CfgFunctions.hpp
Missionframework/KP/KPGUI/KPGUI_classes.hpp
Missionframework/KPLIB_debriefs.hpp
Missionframework/description.ext
Missionframework/scripts/client/CfgFunctions.hpp
Missionframework/scripts/server/CfgFunctions.hpp
Missionframework/ui/liberation_arsenal.hpp
Missionframework/ui/liberation_build.hpp
Missionframework/ui/liberation_deathscreen.hpp
Missionframework/ui/liberation_deploy.hpp
Missionframework/ui/liberation_endscreen.hpp
Missionframework/ui/liberation_halo.hpp
Missionframework/ui/liberation_logistic.hpp
Missionframework/ui/liberation_menu.hpp
Missionframework/ui/liberation_notifications.hpp
Missionframework/ui/liberation_permissions.hpp
Missionframework/ui/liberation_production.hpp
Missionframework/ui/liberation_recycle.hpp
Missionframework/ui/liberation_repackage_fob.hpp
Missionframework/ui/liberation_secondary.hpp
Missionframework/ui/liberation_squad.hpp
Missionframework/ui/liberation_titles.hpp
Missionframework/ui/liberation_tutorial.hpp
Missionframework/ui/mission_params.hpp
Missionframework/ui/standard_controls.hpp

| Q | A |
| --- | --- |
Made classes definitions have the `{` in the same line. Also removed these ` : ` with `: `, changed indentation to spaces and removed empty lines.
Also added more description of the parameters used in the description.ext file.

0.96.7 hpp cleaning

---

CHANGELOG.md
Missionframework/stringtable.xml

Inserted translation into Czech language

Aktualizovat soubor stringtable.xml

---

Missionframework/stringtable.xml

| Q | A |
| --- | --- |
| Bug fix? |  no |
| New feature? |  no |
update Italian localization up to v0.96.8

[v0.96.8] update Italian localization

---

Missionframework/scripts/server/resources/manage_logistics.sqf

minor bugfix

---

Missionframework/scripts/client/actions/open_arsenal.sqf
Missionframework/scripts/client/tutorial/fn_tutorial.fsm

| Q | A |
| --- | --- |
| Bug fix? | no | 
- Replace the "KP_liberation_fob_vehicle" found in the lines 494 and 505 for the right variable "KPLIB_param_fobVehicle"

Update tags in 0.96.8

---

Missionframework/scripts/client/misc/fn_initArsenal.sqf

| Q | A |
| --- | --- |
Fix undefined variable causing initArsenal not to function properly
fix initArsenal.sqf
- [ x] Local MP

Fix initArsenal.sqf undefined variable error

---

Missionbasefiles/kp_liberation.lythium/mission.sqm

| Q | A |
| --- | --- |
Jbad changed their `CfgPatches` entries breaking old missions and mods.
This changes removes the need to use the compat mod https://steamcommunity.com/sharedfiles/filedetails/?id=2442475820

Fix required addons on Lythium after changes in Jbad
