Missionframework/scripts/client/misc/init_arsenal.sqf
This commit disables weapon blacklist filtering when blacklist array is not defined. 
I have noticed that when blacklist arrays are empty in preset then there are some errors in RPT. This fixes these errors.
=> Disable blacklist filtering when array not defined

Missionframework/presets/apex_tanoa.sqf, Missionframework/presets/custom.sqf, Missionframework/presets/rhs.sqf, Missionframework/presets/rhs_bw.sqf, Missionframework/presets/rhs_takistan.sqf, Missionframework/presets/vanilla.sqf, Missionframework/scripts/shared/classnames.sqf, Missionframework/scripts/shared/functions/F_getCommander.sqf
Remove _commander_classname_ from presets and update _F_getCommander_ function to check is player a commander depending on unit name which is already used to give zeus ownership.
There is no point to have this classname in presets when commander slot is defined in mission (unit with name _commandant_)
=> Check is player commander via unit name instead of classname

Missionframework/scripts/client/build/do_build.sqf
This change moves `KP_vector` outside loop so it's not reset to default `true` between every built object. 
Makes easier to build long walls on slope ;-)
=> Terrain aligment sticks between built objects

Missionframework/scripts/client/actions/action_manager.sqf, Missionframework/scripts/client/build/do_build_fob.sqf, Missionframework/scripts/server/remotecall/build_fob_remote_call.sqf
If the connection in the MP Environment isn't too bad, this simple blocking variable should prevent simultaneous FOB building from one container.
=> Fixes #163

Missionframework/scripts/client/build/do_build.sqf
And in addition it prevents saving of preview vehicles (happened if you exit the game with the preview still in front or shut down the mission right after you canceled the build process)
=> Fixes #166

Missionframework/scripts/client/build/do_build.sqf, Missionframework/scripts/server/base/huron_manager.sqf, Missionframework/scripts/server/base/startvehicle_spawn.sqf, Missionframework/scripts/shared/fetch_params.sqf, Missionframework/scripts/shared/functions/F_libSpawnVehicle.sqf, Missionframework/stringtable.xml, Missionframework/ui/mission_params.hpp
This commit adds mission parameter which disables clearing of cargo from vehicles.
This allows to use weapons stored in RHS vehicles, so u can take that BMP down with RPG from captured GAZ ;-)
Cargo clearing is enabled by default to preserve current behaviour.
=> Add param allowing to disable clearing of vehicles inventory/cargo

Missionframework/scripts/server/game/save_manager.sqf
Vehicles loaded from save had their cargo cleared even when it should be disabled by param. Everything that is not a vehicle (crates, containers etc.) is always cleared from cargo.
=> Fix cargo clearing when loading from save

Missionframework/presets/init_presets.sqf, Missionframework/scripts/client/actions/recycle_manager.sqf, Missionframework/scripts/client/build/do_build.sqf, Missionframework/scripts/client/build/open_build_menu.sqf, Missionframework/scripts/shared/functions/F_getGroupType.sqf, Missionframework/scripts/shared/functions/F_kp_isClassUAV.sqf, Missionframework/scripts/shared/liberation_functions.sqf
Automatically detect if vehicles are an UAVs. This allows to remove _uavs_ array from presets.
If u think having array of _uavs_ could be usefull for future functionalities there is alternative (and less "invasive") way to implement this:
_uavs_ array could be built dynamicly in _init_presets.sqf_, with this approach rest of the code could be left intact.
=> Automatically detect if vehicles are an UAV

Missionframework/scripts/server/patrols/send_paratroopers.sqf, Missionframework/scripts/shared/functions/F_libSpawnVehicle.sqf
This fixes #273. 
I have played with these changes on dedicated server for few hours (~3).
Friendly side was configured to EAST and enemy to WEST. Enemy units were _takistani opfor_ and friendly were from _AFRF_, every enemy vehicle crew was correctly forced into WEST side.
=> Fix vehicle crews and paradrop pilots not forced into corect side

Missionframework/scripts/client/actions/do_repackage_fob.sqf, Missionframework/scripts/client/build/do_build.sqf, Missionframework/scripts/server/base/startgame.sqf, Missionframework/scripts/shared/functions/F_kp_setFobMass.sqf, Missionframework/scripts/shared/liberation_functions.sqf
Set fob box mass depending on max sling loadable mass of _huron_ helicopter.
Mass of fob can have minimum of 1000 and maximum of 3000. If max sling loadable mass of _huron_ is not in this range it will be lowered or increased to fit into this range.
After this PR, #271 _should_ be perfectly playable.
=> Calculate fob box mass so it is always slingloadable

Missionframework/presets/blufor/3cbBAF.sqf, Missionframework/presets/blufor/apex.sqf, Missionframework/presets/blufor/bwmod.sqf, Missionframework/presets/blufor/custom.sqf, Missionframework/presets/blufor/rhs_afrf.sqf, Missionframework/presets/blufor/rhs_usaf.sqf, Missionframework/presets/blufor/rhs_usaf_d.sqf
Since #272 there is no need for uav array in preset files. It is now automatically detected if spawned object is an uav.
=> Remove unused uavs array from presets

Missionframework/presets/init_presets.sqf, Missionframework/scripts/client/build/do_build.sqf, Missionframework/scripts/server/game/save_manager.sqf
**When merged this pull request will:**
- fix objects not saving/respawning in the exact position they were left at - this has been an issue for the longest time and caused player-built FOBs to scramble slightly after a savegame reload, sometimes moving props up to a few meters away from their original spawn location
- fix the building menu from detecting ground items (magazines, mags, uniforms, etc.) aswell as corpses as obstructions when attempting to build vehicles or logistics items
**Note:** due to the fixes done to the save manager, the savegame format will change slightly, in that the buildings data now holds 2 vectors for an object's orientation (`vectorDirVisual` and `vectorUpVisual` for use in `setVectorDirAndUp`) rather than 1 vector (`vectorUp`?) and 1 number (`getDir`). …
=> Fixed props saving incorrectly and buildmenu obstructions

Missionframework/init.sqf, Missionframework/scripts/shared/defines.hpp, Missionframework/scripts/shared/fetch_params.sqf
As we discussed earlier on Discord, I have moved saveable parameters to be loaded by server only. Clients will wait for server to load everything.
I have created `shared/defines.hpp`  file which contains macros used to load parameters. Also values used to convert params to floats were moved here, if you think this was not a good decision feel free to revert this part ;)
=> Move parameters loading to server only.

Missionframework/scripts/shared/functions/F_rearmVehicle.sqf, README.md
`setVehicleAmmoDef` resets vehicle weapons to these defined in their base config, this means that vehicles with dynamic loadout loose their customizations when rearmed, changing this to `setVehicleAmmo ` fixes the issue.
=> Fix rearm on vehicles with dynamic loadout support

Missionframework/KPLIB_debriefs.hpp, Missionframework/description.ext, Missionframework/modules/00_init/fnc/fn_init_save.sqf, Missionframework/modules/01_core/fnc/fn_core_changeSectorOwner.sqf, Missionframework/modules/01_core/fnc/fn_core_checkWinCond.sqf, Missionframework/modules/01_core/fnc/fn_core_updateSectorMarkers.sqf, Missionframework/modules/01_core/functions.hpp, Missionframework/stringtable.xml
| Q | A |
| --- | --- |
| Fixed issues | #393 |
Implementation of a check for the win condition X. (e.g. all capitals captured)
If the win condition returns true, display a debriefing screen, wipe the save and end the mission.
=> Check win condition, end campaign and wipe save

Missionframework/KPLIB_config.sqf, Missionframework/KPLIB_debriefs.hpp, Missionframework/KPLIB_params.hpp, Missionframework/modules/00_init/fnc/fn_init_configGuard.sqf, Missionframework/modules/00_init/functions.hpp, Missionframework/modules/01_core/fnc/common/fn_common_getAllPlayers.sqf, Missionframework/modules/01_core/functions.hpp, Missionframework/presets/arsenal/custom.sqf, Missionframework/presets/blufor/custom.sqf, Missionframework/presets/civilians/custom.sqf, Missionframework/presets/opfor/custom.sqf, Missionframework/presets/resistance/custom.sqf, Missionframework/stringtable.xml
| Q | A |
| --- | --- |
| Fixed issues | #430   |
Adds functionality that checks most commonly edited files (preset and config) for errors. If error is present in any of these files, mission is ended and user is informed that there are errors in one of the files that were edited by him.
=> Preset and config files syntax error detection

Missionframework/KPLIB_functions.hpp, Missionframework/KPLIB_ui.hpp, Missionframework/init.sqf, Missionframework/modules/02_build/fnc/fn_build_camera_close.sqf, Missionframework/modules/02_build/fnc/fn_build_camera_open.sqf, Missionframework/modules/02_build/fnc/fn_build_camera_ticker_start.sqf, Missionframework/modules/02_build/fnc/fn_build_camera_ticker_stop.sqf, Missionframework/modules/02_build/fnc/fn_build_displayScript.sqf, Missionframework/modules/02_build/fnc/fn_build_setupPlayerActions.sqf, Missionframework/modules/02_build/functions.hpp, Missionframework/modules/02_build/globals.sqf, Missionframework/modules/02_build/initModule.sqf, Missionframework/modules/02_build/ui.hpp, Missionframework/modules/02_build/ui/KPLIB_buildDisplay.hpp, Missionframework/modules/02_build/ui/defines.inc, Missionframework/stringtable.xml
| Q | A |
| --- | --- |
| Fixed issues | #415   |
Initial implementation of build camera. For now it is really simple, it has no resource system integration as it is not ready yet.
- Scrolling the item list zooms camera
- Missing item collision detection
- Camera is not limited to FOB area
- When tab is switched tab buttons "vibrate" a little bit, Might be not possible to fix this, also happens in vanilla zeus. (optionaly _scale_ animation can be removed)
- Camera should be closed when player is killed
- Main display handling script is too **fat**, some logic needs to be moved to outside functions
=> Floating build camera at FOB

CHANGELOG.md, Missionframework/stringtable.xml
| Q | A |
| --- | --- |
| Fixed issues | #449 |
One of the smallest pull requests we'll have I guess.
Changed the name to the naming standard from the BI Forum:
https://forums.bohemia.net/forums/topic/217676-mission-name-standard/
=> Mission name to BI forum convention

Missionframework/stringtable.xml
Update stringtable formatting according to .editorconfig
| Q | A |
| --- | --- |
| Fixed issues | -  |
Stringtable file uses tab indentation which is incorrect as our .editorconfig has set spaces for indentation.
This PR fixes that.
=> Fix stringtable whitespace

Missionframework/KP_GUI/A3_defines.hpp
| Q | A |
| --- | --- |
| Bug fix? | no|
| Fixed issues | -  |
Updated vanilla UI classes defines syntax. Current syntax is incompatible with SQF Lint and is breaking the parser.
(this was in older files but I guess it got lost in some refactoring)
=> Update A3_defines array syntax for SQF Lint

.vscode/settings.json, Missionframework/modules/02_build/fnc/fn_build_displayScript.sqf, Missionframework/modules/99_playerMenu/fnc/fn_plm_showRankData.sqf, Missionframework/modules/99_playerMenu/ui/KP_playerMenu.hpp, Missionframework/stringtable.xml
| Q | A |
| --- | --- |
| Fixed issues | #471 |
Small fixes and updates for the sprint 4 result.
Note: Currently we can't fix the "directly close bug" for the admin menu as it only contains buttons. Later I guess we'll add a small "statistics/info area" at the top of the dialog and make sure one of the dynamic text controls will be the first focus.
=> V0.97 post sprint 4 fixes/updates

Missionframework/modules/01_core/fnc/fn_core_handleVehicleSpawn.sqf, Missionframework/modules/01_core/fnc/fn_core_setupPlayerActions.sqf, Missionframework/modules/01_core/functions.hpp, Missionframework/modules/01_core/scripts/server/eventLoop.sqf, Missionframework/modules/02_build/fnc/fn_build_setupPlayerActions.sqf
| Q | A |
| --- | --- |
| Bug fix? | yes|
| Needs wipe? | no|
| Fixed issues | -|
Post Sprint 5 `addAction` tweaks, small vehicle respawn action handling refactor
=> V0.97 post Sprint 5 addActions tweaks

Missionbasefiles/kp_liberation.Altis/mission.sqm
| Q | A |
| --- | --- |
Fix redeploy action available only on part of ship
=> Move Base marker on Altis

Missionframework/modules/02_build/fnc/fn_build_addToSelection.sqf, Missionframework/modules/02_build/fnc/fn_build_boundingBoxPFH.sqf, Missionframework/modules/02_build/fnc/fn_build_displayLoad.sqf, Missionframework/modules/02_build/fnc/fn_build_displayPlaceObject.sqf, Missionframework/modules/02_build/fnc/fn_build_displaySetMode.sqf, Missionframework/modules/02_build/fnc/fn_build_displayTabClick.sqf, Missionframework/modules/02_build/fnc/fn_build_drawBoundingBox.sqf, Missionframework/modules/02_build/fnc/fn_build_handleDrag.sqf, Missionframework/modules/02_build/fnc/fn_build_handleKeys.sqf, Missionframework/modules/02_build/fnc/fn_build_handleMouse.sqf, Missionframework/modules/02_build/fnc/fn_build_handleRotation.sqf, Missionframework/modules/02_build/fnc/fn_build_objectUnderCursor.sqf, Missionframework/modules/02_build/fnc/fn_build_start.sqf, Missionframework/modules/02_build/fnc/fn_build_stop.sqf, Missionframework/modules/02_build/fnc/script_components.hpp, Missionframework/modules/02_build/functions.hpp, Missionframework/modules/02_build/globals.sqf, Missionframework/modules/02_build/ui/KPLIB_buildDisplay.hpp
| Q | A |
| --- | --- |
| Bug fix? | yes /  |
| New feature? | yes|
| Needs wipe? | no|
| Fixed issues | -|
Another big chunk of #470 was done in this PR.
=> Build camera further improvements

Missionframework/modules/26_cratefiller/fnc/fn_cratefiller_getNearStorages.sqf
| Q | A |
| --- | --- |
| Fixed issues | #603-2|
This PR fixes `The cratefiller shows groundWeaponHolder as valid storage spaces`.
* ACE
=> fixed cf recognizing "Ground" as inventory

Missionframework/modules/11_permission/fnc/fn_permission_checkVehiclePermission.sqf, Missionframework/modules/11_permission/fnc/fn_permission_postInit.sqf
| Q | A |
| --- | --- |
| Fixed issues | #603-4 |
This PR fixes `The permission kicks players out when seat switching in vehicles with missing permission`.
=> fixed "The permission kicks players out when seat switching in vehicles with missing permission"

Missionframework/modules/23_logistic/fnc/fn_logistic_refreshTargets.sqf, Missionframework/modules/26_cratefiller/fnc/fn_cratefiller_getNearStorages.sqf
| Q | A |
| --- | --- |
| Fixed issues | #603-5 |
This PR fixes `Different objects than vehicles aren't recycleable` .
Also the resupply menu now filters the vehicles when ACE resupply is enabled, so that only ACE fuel/rearm vehicles will be displayed.
* ACE
=> fixed "Different objects than vehicles aren't recycleable"

Missionframework/presets/blufor/apex.sqf, Missionframework/presets/blufor/custom.sqf
| Q | A |
| --- | --- |
| Bug fix? | No |
| New feature? | Yes |
| Needs wipe? | No |
| Fixed issues | N/A |
Added several CUP vehicles to the NATO and Pacific NATO presets
=> CUP additions to NATO presets

Missionframework/stringtable.xml
I added some missing russian translations (not all) and fixed typos in existing translations.
| Q | A |
| --- | --- |
Added missing russian translations and fixed typos in **stringtable.xml**
=> Fix typos and add missing russian translations

Missionframework/presets/blufor/CUP_ACR_Desert.sqf, Missionframework/presets/blufor/CUP_ACR_Woodland.sqf, Missionframework/presets/blufor/CUP_BAF_Desert.sqf, Missionframework/presets/blufor/CUP_BAF_Woodland.sqf, Missionframework/presets/blufor/CUP_CDF.sqf, Missionframework/presets/blufor/CUP_USA_Desert.sqf, Missionframework/presets/blufor/CUP_USA_Woodland.sqf, Missionframework/presets/blufor/CUP_USMC_Desert.sqf, Missionframework/presets/blufor/CUP_USMC_Woodland.sqf, Missionframework/presets/blufor/apex.sqf, Missionframework/presets/blufor/custom.sqf, README.md
| Q | A |
| --- | --- |
| Bug fix? | No |
| New feature? | No |
| Needs wipe? | No |
| Fixed issues | N/A |
CUP Presets still had the Nemmera repair vehicle that I forgot to remove as well as had their towing tractors all over the place and sometimes even in two spots. This PR will fix those small issues.
=> Small 0.96.6 CUP Tweaks

Missionframework/scripts/server/sector/manage_one_sector.sqf, Missionframework/scripts/shared/fetch_params.sqf, Missionframework/stringtable.xml, Missionframework/ui/mission_params.hpp, README.md
| Q | A |
| --- | --- |
Makes sector despawn time more dynamic by increasing the time of sector deactivation delay by multiplying default deactivation time by the amount of minutes the sector was activated, starting from fifth activation minute. 
Increased despawn time is added to base despawn time.
```
IF minutes_running < 5:
despawn_time = BASE_DESPAWN_TIME
ELSE
despawn_time = BASE_DESPAWN_TIME + ((minutes_running - 5) * BASE_DESPAWN_TIME )
```
`BASE_DESPAWN_TIME` is ~60s by default (depending on scheduler load)
* Nothing
=> v0.96.6 - Increasing sector despawn time

Missionframework/scripts/server/ai/building_defence_ai.sqf, Missionframework/scripts/shared/functions/F_kp_createClearance.sqf, README.md
| Q | A |
| --- | --- |
| Fixed issues | #662 |
With this addition the enemies in buildings are not bound to a fixed 40m search radius for blufor soldiers until they resume their normal movement.
It's now bound to the opfor/blufor ratio and increases if the amount of blufor in relation to the amount of living opfor soldiers raise. It goes up to a maximum if 2/3 of the sectors capture range, set in the config file. (~120m search radius max)
This should make it easier to clean cities if there are only some few enemies left hidden in buildings.
Also a small fix for the remaining light sources after creating a clearance. (#662)
=> V0.96.6 dynamic building ai range

.vscode/settings.json, Missionframework/KPLIB_functions.hpp, Missionframework/modules/01_common/fnc/fn_common_addAction.sqf, Missionframework/modules/02_core/fnc/fn_core_handleSector.sqf, Missionframework/modules/02_core/fnc/fn_core_settings.sqf, Missionframework/modules/02_core/fnc/fn_core_setupPlayerActions.sqf, Missionframework/modules/15_build/README.md, Missionframework/modules/16_garrison/README.md, Missionframework/modules/16_garrison/fnc/fn_garrison_changeOwner.sqf, Missionframework/modules/16_garrison/fnc/fn_garrison_despawn.sqf, Missionframework/modules/26_cratefiller/README.md, Missionframework/modules/27_mission/README.md, Missionframework/modules/28_captive/README.md, Missionframework/modules/28_captive/fnc/fn_captive_addCaptiveActions.sqf, Missionframework/modules/28_captive/fnc/fn_captive_checkSector.sqf, Missionframework/modules/28_captive/fnc/fn_captive_escort.sqf, Missionframework/modules/28_captive/fnc/fn_captive_interrogate.sqf, Missionframework/modules/28_captive/fnc/fn_captive_loadCaptive.sqf, Missionframework/modules/28_captive/fnc/fn_captive_postInit.sqf, Missionframework/modules/28_captive/fnc/fn_captive_preInit.sqf, Missionframework/modules/28_captive/fnc/fn_captive_setAceCaptive.sqf, Missionframework/modules/28_captive/fnc/fn_captive_setCaptive.sqf, Missionframework/modules/28_captive/fnc/fn_captive_setSurrender.sqf, Missionframework/modules/28_captive/fnc/fn_captive_settings.sqf, Missionframework/modules/28_captive/fnc/fn_captive_stopEscort.sqf, Missionframework/modules/28_captive/fnc/fn_captive_unloadCaptive.sqf, Missionframework/modules/28_captive/functions.hpp, Missionframework/modules/README.md, Missionframework/stringtable.xml
| Q | A |
| --- | --- |
| Fixed issues | #531 |
This PR provides the first iteration of the PoW.
This ensures that leftover enemys on a sector capture will surrender and the player is able to interact with them.
=> Prisoners of War

Missionframework/scripts/shared/functions/F_getMobileRespawns.sqf
| Q | A |
| --- | --- |
Fix mobile respawn flickering introduced by removing height check and using `isTouchingGround`. Use both methods so the check should be still more reliable for vehicles with bad models.
=> v0.96.7 - Fix mobile respawn flickering

Missionframework/init.sqf, Missionframework/kp_objectInits.sqf, Missionframework/scripts/server/ai/troup_transport.sqf, Missionframework/scripts/server/civinformant/civinfo_loop.sqf, Missionframework/scripts/server/civinformant/tasks/civinfo_task.sqf, Missionframework/scripts/server/civrep/wounded/civrep_wounded_civs.sqf, Missionframework/scripts/server/game/save_manager.sqf, Missionframework/scripts/server/patrols/manage_one_civilian_patrol.sqf, Missionframework/scripts/server/patrols/manage_one_patrol.sqf, Missionframework/scripts/server/patrols/send_paratroopers.sqf, Missionframework/scripts/server/secondary/convoy_hijack.sqf, Missionframework/scripts/server/secondary/fob_hunting.sqf, Missionframework/scripts/server/secondary/search_and_rescue.sqf, Missionframework/scripts/server/sector/attack_in_progress_fob.sqf, Missionframework/scripts/server/sector/attack_in_progress_sector.sqf, Missionframework/scripts/shared/functions/F_forceBluforCrew.sqf, Missionframework/scripts/shared/functions/F_kp_addObjectInit.sqf, Missionframework/scripts/shared/functions/F_kp_createCrate.sqf, Missionframework/scripts/shared/functions/F_kp_createManagedUnit.sqf, Missionframework/scripts/shared/functions/F_kp_spawnGuerillaGroup.sqf, Missionframework/scripts/shared/functions/F_libSpawnMilitiaCrew.sqf, Missionframework/scripts/shared/functions/F_spawnBuildingSquad.sqf, Missionframework/scripts/shared/functions/F_spawnCivilians.sqf, Missionframework/scripts/shared/functions/F_spawnMilitaryPostSquad.sqf, Missionframework/scripts/shared/functions/F_spawnRegularSquad.sqf, Missionframework/scripts/shared/liberation_functions.sqf
| Q | A |
| --- | --- |
Improvements for object inits. Added support for resource crates and units. To make handling of units initialization easier creation of units managed by liberation Kill-Tracker was moved into separate dedicated function
* None
=> v0.96.7 - Hotfix - Object inits improvements

Missionframework/scripts/server/game/save_manager.sqf
| Q | A |
| --- | --- |
Adds saving of mines around the FOBs.
=> v0.96.7 - Save mines placed around FOBs

Missionframework/presets/arsenal/blacklist.sqf
Bug fix?  New feature?  Sort of in-between.  Addresses a regression (ability to make free turrets/robots and sell them) due to the new DLC adding items not covered by the existing arsenal blacklist.
Needs wipe? | no
Fixed issues | none in the tracker for this issue
Adds all Contact DLC backpack slot items that correspond to assemble-able turrets or bots to the default arsenal blacklist, in keeping with the pattern of such items in previous DLCs and the base game being in the list.
My server uses a long list of mods but this is a simple change that should not impact mod interaction at all.
=> add backpack deployables from Contact DLC to arsenal blacklist

Missionframework/scripts/server/ai/battlegroup_ai.sqf, Missionframework/scripts/server/ai/troup_transport.sqf, Missionframework/scripts/server/battlegroup/random_battlegroups.sqf, Missionframework/scripts/server/battlegroup/spawn_battlegroup.sqf, Missionframework/scripts/server/patrols/send_paratroopers.sqf, README.md
| Q | A |
| --- | --- |
| Fixed issues | #622 |
Some format tweaks to the old battlegroup scripts. Also spawns the infantry for battlegroup transport land vehicles closer (1000m reduced to 500m) at the target destination. Furthermore we never catched helicopters added to battlegroup arrays and to transport array in opfor presets. Now if a battlegroup vehicle is also in the transport array, it'll either use the troop transport script when not an air vehicle and spawns the send_paratroopers script, if it's an air vehicle.
=> V0.96.7 battlegroup tweaks

Missionframework/scripts/client/misc/init_arsenal.sqf, README.md
| Q | A |
| --- | --- |
| Fixed issues |  |
Automatically whitelist classes defined through CBA Disposable Launchers
* CBA A3 + SFP
=> Add support for disposable launchers

Missionframework/CfgFunctions.hpp, Missionframework/functions/fn_addRopeAttachEh.sqf, Missionframework/functions/fn_getOpforSpawnPoint.sqf, Missionframework/kp_objectInits.sqf, Missionframework/scripts/server/base/huron_manager.sqf, Missionframework/scripts/server/base/startvehicle_spawn.sqf, README.md
| Q | A |
| --- | --- |
As it was sometimes reported, that people loose e.g. the FOB box due to breaking ropes on dedicated servers while transporting it with the Potato 01 helicopter, I've added a locality change for slingloaded cargo. It'll add a `ropeAttach` EH to every helicopter which is able to slingload cargo. The EH will change the locality of the cargo to the helicopter pilot, which will fix the desyncs and resulting rope breaks while flying.
Also the start vehicles are now also checked for possible objectInit entries.
=> 0.96.7 Locality change of slingloaded cargo

Missionframework/CfgFunctions.hpp, Missionframework/description.ext, Missionframework/functions/fn_setDiscordState.sqf, Missionframework/init.sqf, Missionframework/scripts/client/ui/ui_manager.sqf, README.md
| Q | A |
| --- | --- |
Adds basic Discord rich presence functionality by adding support and utilization of the [Discord Rich Presence Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1493485159) from @ConnorAU.
It simply just shows if you're at a FOB, at a sector or in the field. This can and might be enhanced later, of course.
=> 0.96.7 Basic Discord Rich Presence

.gitignore, Missionframework/functions/fn_getSaveData.sqf, Missionframework/scripts/client/actions/do_recycle.sqf, Missionframework/scripts/client/build/do_build.sqf, Missionframework/scripts/client/build/do_sector_build.sqf, Missionframework/scripts/client/misc/playerNamespace.sqf, Missionframework/scripts/server/game/cleanup_vehicles.sqf, Missionframework/scripts/server/remotecall/add_logiTruck_remote_call.sqf, Missionframework/scripts/server/remotecall/build_fac_remote_call.sqf, Missionframework/scripts/server/remotecall/del_logiTruck_remote_call.sqf, Missionframework/scripts/server/resources/manage_logistics.sqf, Missionframework/scripts/server/resources/manage_resources.sqf, Missionframework/scripts/server/resources/recalculate_resources.sqf, README.md
| Q | A |
| --- | --- |
Lowered the positive margin for the FOB ranges in saving, cleanup, recycle, etc.
Also set a fixed value for the range checks concerning production sectors for e.g. find the storage area of the sector.
Aims to lower the possiblity of unwanted behavior, if the FOB range is highly increased via config.
Furthermore I've added a simple visual aid for the FOB range while build mode is enabled. Maybe this also shows how large the default radius of 125m really is.
=> 0.96.7 Range adjustments

Missionframework/functions/fn_crateFromStorage.sqf, Missionframework/functions/fn_createCrate.sqf, Missionframework/functions/fn_getGroupType.sqf, Missionframework/functions/fn_getSaveData.sqf, Missionframework/functions/fn_handlePlacedZeusObject.sqf, Missionframework/presets/init_presets.sqf, Missionframework/scripts/client/actions/do_recycle.sqf, Missionframework/scripts/client/actions/recycle_manager.sqf, Missionframework/scripts/client/build/do_build.sqf, Missionframework/scripts/client/build/open_build_menu.sqf, Missionframework/scripts/client/markers/empty_vehicles_marker.sqf, Missionframework/scripts/client/misc/vehicle_permissions.sqf, Missionframework/scripts/client/remotecall/remote_call_prisonner.sqf, Missionframework/scripts/server/game/cleanup_vehicles.sqf, Missionframework/scripts/server/game/zeus_synchro.sqf, Missionframework/scripts/server/resources/unit_cap.sqf
| Q | A |
| --- | --- |
The changes in the `init_presets.sqf` made most classname collection arrays having the classnames in all lowercase. This caused issues in e.g. do_build or save_manager, as we use `in` there many times, which is case sensitive.
Hopefully I've found all occurances. Another look/search beside of the review here would be highly appreciated.
=> 0.96.7 Fixed issues due to `toLower` usage in presets

CHANGELOG.md, Missionframework/functions/fn_getSaveData.sqf, Missionframework/scripts/server/game/save_manager.sqf
| Q | A |
| --- | --- |
Saves crates at blufor sectors which spawn crates on activation. (`factory_`/`capture_`).
=> 0.96.7 Save/Load of sector activation crates

Missionframework/scripts/client/actions/do_repackage_fob.sqf
| Q | A |
| --- | --- |
| New feature? |  no |
Adds a missing semi-colon to `do_repackage_fob`
=> Add missing semicolon to do_repackage_fob

Missionframework/functions/fn_spawnRegularSquad.sqf, Missionframework/functions/fn_spawnVehicle.sqf, Missionframework/kp_liberation_config.sqf, Missionframework/scripts/server/sector/fn_spawnSectorCrates.sqf, Missionframework/scripts/server/sector/fn_spawnSectorIntel.sqf
| Q | A |
| --- | --- |
Possible fix for creating possible endless loops while searching for a suitable spawn position. At least it'll give more insight in possible issues due to added logging.
Furthermore a fix for an error in intel spawning.
=> 0.96.7 Exit while on spawnpos search

CHANGELOG.md, Missionframework/presets/enemies/gm_east.sqf
| Q | A |
| --- | --- |
Just started a session in GM version and that damn harmless thing was driving around everywhere.
=> Lower the chance for unarmed BRDM in GM East enemy preset

CHANGELOG.md, Missionframework/functions/fn_getSaveData.sqf, Missionframework/kp_liberation_config.sqf, Missionframework/scripts/server/game/save_manager.sqf, Missionframework/scripts/server/game/spawn_radio_towers.sqf
Closes #812
| Q | A |
| --- | --- |
Adds an array to the config file to set the radio tower classnames which spawn at the radio tower sectors.
This is selected random on campaign start and is afterwards persistent during the campaign.
=> [0.96.7a] Radio tower classnames array

CHANGELOG.md, Missionframework/arsenal_presets/gm_east.sqf, Missionframework/arsenal_presets/gm_west.sqf, Missionframework/kp_liberation_config.sqf, Missionframework/presets/blufor/gm_east.sqf, Missionframework/presets/blufor/gm_east_win.sqf, Missionframework/presets/blufor/gm_west.sqf, Missionframework/presets/blufor/gm_west_win.sqf, Missionframework/presets/opfor/gm_east.sqf, Missionframework/presets/opfor/gm_east_win.sqf, Missionframework/presets/opfor/gm_west.sqf, Missionframework/presets/opfor/gm_west_win.sqf
| Q | A |
| --- | --- |
* Added helicopters from the GM update to blufor and opfor presets for East and West Germany.
* Added ACE, TFAR and ACRE items to the GM arsenal presets.
=> [0.96.7a] GM Preset Updates

CHANGELOG.md, Missionframework/functions/curator/fn_initCuratorHandlers.sqf, Missionframework/scripts/client/init_client.sqf, Missionframework/scripts/shared/fetch_params.sqf, Missionframework/stringtable.xml, Missionframework/ui/mission_params.hpp
| Q | A |
| --- | --- |
| Bug fix? | yes  |
Remove all addons for limited zeus, add param to disable zeus for commander.
No changelog entry as it's part of previous PR to 0.96.7a.
=> Remove all addons for limited zeus, add param to disable zeus for commander
